services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: hospital_booking_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./database:/app/database:rw
      - ./logs:/app/logs:rw
    networks:
      - hospital_network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: hospital_booking_frontend
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - hospital_network
    restart: unless-stopped

networks:
  hospital_network:
    driver: bridge

volumes:
  hospital_db:
    driver: local
  hospital_logs:
    driver: local
